steps:

- name: "mikewilliamson/usesthis-ci"
  id: start_arangodb
  entrypoint: "/bin/sh"
  args: [ "-c", "
  docker run -d --network=cloudbuild -p=8529:8529 --name=arangodb mikewilliamson/aci \
  && /wait-for arangodb:8529
  " ]

- name: "gcr.io/cloud-builders/npm"
  id: web_install_deps
  dir: web
  args: ["install"]

- name: "gcr.io/cloud-builders/npm"
  id: web_lint
  dir: web
  args: ["run", "lint"]

- name: "mikewilliamson/usesthis-ci"
  id: test_web
  timeout: 600s
  dir: web
  env:
  - "USESTHIS_TEST_DB_URL=http://arangodb:8529"
  - "USESTHIS_DB_USER=root"
  - "USESTHIS_DB_PASSWORD=test" # public pw for the public mikewilliamson/aci image
  entrypoint: "/bin/sh"
  args: [ "-c", "npm t" ]

- name: 'gcr.io/cloud-builders/npm'
  id: bundle
  dir: web
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [[ "$BRANCH_NAME" == "master" ]]; then
      npm run build:server && NODE_ENV=production npm run bundle
    else
      exit 0;
    fi

- name: 'gcr.io/cloud-builders/docker'
  id: build_web
  dir: web
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [[ "$BRANCH_NAME" == "master" ]]; then
      docker build -t gcr.io/$PROJECT_ID/usesthis-web:$SHORT_SHA . \
      && docker push gcr.io/$PROJECT_ID/usesthis-web
    else
      exit 0;
    fi
