steps:

- name: "mikewilliamson/usesthis-ci"
  id: start_arangodb
  entrypoint: "/bin/sh"
  args: [ "-c", "
  docker run -d --network=cloudbuild -p=8529:8529 --name=arangodb mikewilliamson/aci \
  && /wait-for arangodb:8529
  " ]

- name: "gcr.io/cloud-builders/npm"
  dir: web
  args: ["install"]

- name: "mikewilliamson/usesthis-ci"
  id: test_web
  timeout: 600s
  dir: web
  env:
  - "USESTHIS_TEST_DB_URL=http://arangodb:8529"
  - "USESTHIS_DB_USER=root"
  - "USESTHIS_DB_PASSWORD=test" # public pw for the public mikewilliamson/aci image
  entrypoint: "/bin/sh"
  args: [ "-c", "npm t" ]

- name: 'gcr.io/cloud-builders/docker'
  id: build_api
  dir: api
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [[ "$BRANCH_NAME" == "master" ]]; then docker build -t mikewilliamson/usesthis-web:$SHORT_SHA . && docker push mikewilliamson/usesthis-web; else exit 0; fi
